### ISSUE TITLE
2: Make it possible to activate a washing machine

### ISSUE THREAD

**Issue by MartinBruun** [MartinBruun/P6#24]
**Who wants the feature?**
Stakeholder: Morten Bruun Jacobsen

**The user story**
As an Aparment Owner i want a machine that can turn on the washing machine because my tenants need to be able to do washes.

**Any ideas for how it can be done?**
Option 1 might be a Raspberry Pi which gets some custom pre-build elements, which can be setup remotely at the washing machine.

Option 2 might be be the same, but an Arduino instead.

**Additional context**
No extra context as of now

**Comment by saxjax** [comment]
Components in this solution:
Program raspberry to send on off signal to pin via GPIOzerro: Done
connect pi to relay.
connect machine to relay. (evt en stikkontakt som kan tændes og slukkes via pi.)
Check that machine can actually be started and stopped by cutting/turning-on the power (strøm måler I kontakt, https://www.proshop.dk/Smart-Home/Pro-WiFi-Smart-Plug-16A-with-Energy-Monitoring/2915818?utm_source=google&utm_medium=cpc&utm_campaign=searchengine&gclid=Cj0KCQiA09eQBhCxARIsAAYRiymiudWWo2lriHSaYmkLW4qp7Rqof1BbA-SbWPuNmJjAWDrEyJ5gQkkaAvWbEALw_wcB)

Setup Flask: with endpoints that triggers above program: Done
Expose endpoint to mobile app :
Make pi's endpoint accessible via mobilephone (wifi?,bluetooth?)

NOTE: consider security, 
how do we secure the connection so others can not log in.?
how do we secure that the machine lock/unlock is separated from the setup of the pi ?(physical separation, with a lock, setup via usb, different exposed ports, 5001 user, 5022 admin, and codeprotected)

How do we ensure that a lock that has been opened is also used?
