### ISSUE TITLE
make an integrationtest, that simulates what happens when a device is connecting to wifi--3g. and when already connected to washee,when  not able to connect to 3g ....wifi...in different orders.

### ISSUE THREAD

**Issue by saxjax** [MartinBruun/P6#263]

**Comment by saxjax** [comment]
sorry den er skrevet fra mobil.
lav en test som simulerer de forskellige scenarier med skift mlm 3g til wifi og tilbage igen. måske er det slet ikke muligt.

Jakob skov Søndergård
Rolighedsvej 5
9510 Arden
Tlf 53379559
Mail ***@***.***

**Comment by MartinBruun** [comment]
Have been merged with another issue
