### ISSUE TITLE
(chapter 05) Display images side by side

### ISSUE THREAD

**Issue by mkju19** [MartinBruun/P6#291]
**What needs to be written?**
The images in this section needs to be put side by side instead of below eachother

**Why do we need it?**
To save space

**Comment by saxjax** [comment]
why do we need it to give an easy overview of the interface for the reader

**Comment by saxjax** [comment]
show the two versions of 
	A: Calendar and Timepicker no greenScore
B: Calendar and Timepicker with greenScore
