### ISSUE TITLE
(03 chapter related work) should be less about washing machines more about other studies

### ISSUE THREAD

**Issue by saxjax** [MartinBruun/P6#292]
**What needs to be written?**
Related work
it should say something abaout how other people have designed their interfaces, maybe they can be categorized, other work that handles nudging, other work that handles displaying environmental impact to the user(smat power sockets..⟩ .

Related work (missing: what strategies do other studies use to make people shifting behaviour for sustainability, some systems encentifies people to make more green decisions, others just displays the information like the smart plug, others use gamification.... )
	Don't give the history of washingmachines here, put it in the introduction
	It is weird that we explain about the history of washing in the beginning of this section, 
	it needs some segway into this
	--it should say something abaout how other people have designed their interfaces, maybe they can be categorized, other work that handles nudging, other work that handles displaying environmental impact to the user(smat power sockets...) .
	go to talking about home laundry in the "washing with the wind study", and that we can have a greater impact if we affect shared laundries because that impacts 10-20 users and not just 2 adults in a household. sp if we make the habits of the users of a shared laundry more sustainable then it will potentially have a bigger impact than it would with just one house hold.
	Having many users share a single machine also makes conducting the study easier for us, because we can collect data regarding the same environment and the same availlability conditions for all the users.
	
	
	tech has been deployed to support sustainable energy usage in many ways. There have even been a study trying to help people change habits when washing, however in those studies there have not been studies involving communal washing. therefore we engage with this challenge of designing technologies for encourraging shared washing in appartments with a shared laundry, and we want to know , how can we design a system to shift behaviour towards washing on the most environmentally sustainable times.
	
Strategy from washing with the wind: was to  try out just displaying the information, then penalising "bad" behaviour,  completely disallowing the possibility of behaving bad.
	Showing sustainability related information: 
	Smart plugs shows the consumption, SmartThermostat has a green leaf that helps the user find the sustainable choice.
	
	
	Washee is great as a researching platform where you can study techniques and use interface design to support shifting of  peoples  behaviors based on a mobilePhone platform.
	
in the next section we will explain the development of the prototype.....

**Why do we need it?**
show that we are acquainted with state of the art research in the field of green Energy consumption habits

**Source references (if applicable)**
List any relevant sources here:
Washing with the wind
Smart plugs

**Comment by MartinBruun** [comment]
Agree. The start of "Related Work" and "Laundromat in modern times" should at a minimum be put up into the introduction
