### ISSUE TITLE
1: Create the proper Dockerfiles (docker-compose?) that represents the problem domain

### ISSUE THREAD

**Issue by MartinBruun** [MartinBruun/P6#30]
**Who wants the feature?**
Product Owner: Martin BM

**The user story / why is it necessary?**
To be able to start working, we need to have some form of codebase

**Any ideas for how it can be done?**
Option 1 might be to create a seperate folder with a Dockerfile for each "cyber-physical element", ie. 1 for a server, 1 for the timebox etc.

Option 2 might be to create seperate Dockerfiles in a more Microservices aimed architechture, where each Dockerfile relates to a Module or Service in the overall project.

Option 3 might be to create a repository for each "cyber-physical" element, and have this repository as the "master" repository?

**Additional context**
It is important to figure out how this can be integrated into the CI workflow. If everything has to be build and tested, each PR will take an enormous amount of time (rather than only building/testing the code which have been changed in the PR)

**Comment by MartinBruun** [comment]
There can be made a seperate workflow for each Dockerfile, where it can be set for "on: pull_request: paths: -'/file_with_app' it seems:
https://github.community/t/is-it-possible-to-run-the-job-only-when-a-specific-file-changes/115484

So that is probably the best solution

**Comment by saxjax** [comment]
Jakob kigger på raspberry og docker til samme
